# Note that this file is not used in production. It is only used for local development. With
# this in mind, the hosts for elastic and postgres are set to the service names in the docker-compose
# because of the bridge network. You can also comment any services that you don't need for local

version: "3.9"
services:
  postgres:
    container_name: postgres_wallet
    image: postgis/postgis
    networks:
      - wallet_network
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  wallet_network:
    driver: bridge
volumes:
  pgdata:

